target: TenYearCHD
random_state: 42
test_size: 0.2

model_name: DummyClassifier

evaluation:
  metrics: [auc, f1, accuracy, precision, recall, log_loss]
  log_metrics: [classification_report, confusion_matrix]
  plot_metrics: []

preprocessing_steps:
